# Generated by Django 4.1.7 on 2023-09-16 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.DateField(default=datetime.date(2023, 9, 16)),
        ),
    ]
